[package]
name = "tapl-rust"
version = "0.1.0"
authors = ["Kyle Lin <kylejlin.us@gmail.com>"]
edition = "2018"

[lib]
name = "tapl_rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
